-- Title: IELTS Writing Scoring Database Schema
-- Version: 1.0.0
-- Date: 2026-01-23
-- Author: Trae AI Architect

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Users Table
-- Stores user account and subscription information.
create table public.users (
  id uuid references auth.users not null primary key, -- Links to Supabase Auth
  email text not null,
  plan text check (plan in ('free', 'pro', 'enterprise')) default 'free',
  subscription_status text check (subscription_status in ('active', 'past_due', 'canceled', 'none')) default 'none',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Users can only view and edit their own profile.
alter table public.users enable row level security;
create policy "Users can view own profile" on public.users for select using (auth.uid() = id);
create policy "Users can update own profile" on public.users for update using (auth.uid() = id);


-- 2. Essays Table
-- Stores the raw essay content submitted by the user.
create table public.essays (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  task_type text check (task_type in ('task1', 'task2')) not null,
  question_text text not null, -- The prompt/question
  essay_body text not null,
  word_count integer not null,
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Users can only see their own essays.
alter table public.essays enable row level security;
create policy "Users can view own essays" on public.essays for select using (auth.uid() = user_id);
create policy "Users can insert own essays" on public.essays for insert with check (auth.uid() = user_id);

-- Index for fast history queries by user and date.
create index idx_essays_user_submitted on public.essays(user_id, submitted_at desc);


-- 3. Evaluations Table
-- Stores the scoring results and feedback generated by the LLM.
create table public.evaluations (
  id uuid default uuid_generate_v4() primary key,
  essay_id uuid references public.essays(id) on delete cascade not null,
  
  -- JSONB Structure for band scores: { "TR": 6.0, "CC": 6.5, "LR": 7.0, "GRA": 6.0 }
  band_scores jsonb not null,
  
  overall_band numeric(3,1) not null,
  
  -- JSONB Structure for feedback: 
  -- { "TR": { "strengths": [], "weaknesses": [] }, "tips": [], "corrections": [] }
  detailed_feedback jsonb not null,
  
  -- Stores which version of the rubric was used (for audit/consistency)
  -- { "version": "v1", "mapping_id": "..." }
  rubric_mapping jsonb not null default '{"version": "v1"}',
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Users can view evaluations linked to their essays.
alter table public.evaluations enable row level security;
create policy "Users can view own evaluations" on public.evaluations for select using (
  exists (select 1 from public.essays where essays.id = evaluations.essay_id and essays.user_id = auth.uid())
);

-- Index for retrieving evaluation by essay_id
create index idx_evaluations_essay_id on public.evaluations(essay_id);


-- 4. Attempts Table
-- Tracks multiple attempts for the same "logical" essay task to show improvement.
-- Note: 'essay_id' here refers to the specific submission. 
-- To track "same question, different drafts", we might rely on the frontend grouping by 'question_text' or add a 'parent_essay_id' in essays.
-- Here, we assume a linear progression where each row is a snapshot of progress.
create table public.attempts (
  id uuid default uuid_generate_v4() primary key,
  essay_id uuid references public.essays(id) on delete cascade not null,
  evaluation_id uuid references public.evaluations(id) on delete cascade not null,
  
  attempt_no integer not null default 1,
  
  -- Difference from previous attempt: { "TR": +0.5, "overall": +0.5 }
  delta_band jsonb, 
  
  trend_comment text, -- e.g. "Great job improving your Cohesion!"
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Users can view their own attempts.
alter table public.attempts enable row level security;
create policy "Users can view own attempts" on public.attempts for select using (
  exists (select 1 from public.essays where essays.id = attempts.essay_id and essays.user_id = auth.uid())
);

-- Index for trend charts (getting attempts in order)
create index idx_attempts_essay_attempt on public.attempts(essay_id, attempt_no);


-- Summary Checksum
-- Total Tables: 4
-- Total Indexes: 3 (explicit) + PK indexes
-- Expected Row Growth:
--   Users: Low
--   Essays: High (1 per submission)
--   Evaluations: High (1 per essay)
--   Attempts: High (1 per essay)
